[package]
name = "ppm-viewer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ppmv"
path = "src/main.rs"

[dependencies]
eframe = "0.32.3"


[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
